### ISSUE TITLE
Use pageshow event instead of load

### ISSUE THREAD

**Issue by isocroft** [craigbuckler/progressive-image.js#17]
I would like the awesome authors of this awesome library snippet to consider the "pageshow" event over the "load".

This is just to increase support for SPA libaries by binding to this late event which fires much more later after the "load" event and has support for back/forward buttons (browsers like Firefox/Edge don't fire the "load" event during history navigation - [details here](https://developer.mozilla.org/en-US/docs/Web/Events/pageshow)) for consistent behavior.

Also browser support for this event is [MASSIVE both on desktop & mobile](https://developer.mozilla.org/en-US/docs/Web/Events/pageshow#Browser_compatibility)!

I also want to get a critique on this from you guys.

Plus, i really love the idea and "minimal-ity" used in this library (seriously - IntersectionObservers would be an overkill) and i wish to make it better.

Kudos!!

**Comment by craigbuckler** [comment]
Thanks @isocroft.

Have you had trouble using it in SPAs? I guess the main issue would be that, when you switch to a new "page", any images placed into view will not be loaded until the user scrolls. One possible way around that, JS lines 15-17 currently have:

```js
var observer = new MutationObserver(function() {
      if (pItem.length !== pCount) inView();
});
```

Try changing that to:

```js
var observer = new MutationObserver(inView);
```

It could cause some performance issues but it's worth a try.

I'll take a look at the `pageshow` event but I doubt it'll solve all problems since an SPA could change pages without using session history.

I did consider `IntersectionObserver` but an observer must be attached to each progressive image. There could be hundreds, and they can be added dynamically. Admittedly, this code must loop through all images when the page is scrolled, but that is throttled and the number of images reduces as they are replaced. That said, `IntersectionObserver` remains an option (I just wish it's API wasn't so weird!)

**Comment by travisbell** [comment]
I was having a problem where progressive-image.js wouldn't load images in a modal window until the window was scrolled. Changing the above lines fixed this issue.

**Comment by synergixe** [comment]
Which lines fixed this issue ? @travisbell

**Comment by travisbell** [comment]
I changed lines 15-17 as per @craigbuckler's suggestion:

> JS lines 15-17 currently have:
> 
> ```js
> var observer = new MutationObserver(function() {
>       if (pItem.length !== pCount) inView();
> });
> ```
> 
> Try changing that to:
> 
> ```js
> var observer = new MutationObserver(inView);
> ```

**Comment by craigbuckler** [comment]
Apologies for the long delay, but v1.5.0 now supports the window `pageshow` event. The MutationObserver is also more reliable.
