### ISSUE TITLE
Question about using <a> tags

### ISSUE THREAD

**Issue by RubenKos** [craigbuckler/progressive-image.js#2]
Hi Craig,

First of all, thank you for this awesome piece of code and the tutorial on Sitepoint, super helpful!

After implementing this on a few places I was wondering if it possible to not use the <a> tag for the full image? I tried replacing the <a> tag by something like a <span> or a <div> but it doesn't seem to work. My JS experience is limited so I could not figure out where in the JS the <a> is being called.

Would be great if you could help me out here.

Thank you in advance!

**Comment by craigbuckler** [comment]
Thanks @RubenKos.

I think GitHub may have mangled your message. Is it the `<a>` or the `<img>` you want to change in the HTML? A sample of code would be good.

It is done like that for a reason: if JavaScript fails, the user can click the thumbnail to view the full image. That said, there may be situations such as decorative hero images where that wouldn't be required.

Craig

**Comment by RubenKos** [comment]
Thank you for coming back to me so quickly Craig!

I would like to change the `<a>` in the HTML to either a `<span>` or a `<div>`. I know it is done as an `<a>` to provide a fallback which is great, but for a specific situation I would need it to be able to also use different tags.  So as an example I am looking to make something like the following work:

```
<span href="full.jpg" class="progressive replace">
      <img src="tiny.jpg" class="preview" alt="image" />
</span>
```

Hope that helps.

Thank you,
Ruben

**Comment by craigbuckler** [comment]
You're welcome!

Actually, I've got some code to do this but haven't changed this repo because it's referenced in the SitePoint article _(I may do a follow-up at some point)_. I suggest using `<figure>` rather than `div` or `span` but it really doesn't matter. Here's the HTML:

```html
<figure data-href="full.jpg" class="progressive replace">
  <img src="tiny.jpg" class="preview" />
</figure>
```

**Important:** use a `data-href` attribute rather than `href` because that's only valid for anchor tags.

Next, change all references in **progressive-image.css** from `a.progressive` to just `.progressive` so `<figure>` or any other tag is targetted _(I probably should have done that from the start!)_

Finally, we need a few tweaks in **progressive-image.js**:

Replace line 47 (`if (!item || !item.href) return;`) with this code:

```javascript
    var href = item && (item.href || item.getAttribute('data-href'));
    if (!href) return;
```

It will read the `data-href` attribute when it's available. _(`.getAttribute` is used rather than `.dataset` to ensure old browsers work.)_

Next, replace line 55 (now at 56 - `img.src = item.href;`) with:

```javascript
    img.src = href;
```

That's it. The code will work whether you choose to use either

* `<a href="full.jpg" class="progressive replace">` or 
* `<some-other-tag data-href="full.jpg" class="progressive replace">`

for any image replacement.

I hope that helps.
