### ISSUE TITLE
Feature request: provide options to pass an onError handler

### ISSUE THREAD

**Issue by cheuksing** [craigbuckler/progressive-image.js#23]
It would be nice to have an option to handle failed loading images.
So users can do a re-fetch or display something else.

I'd expect something like this,
p.s. I know data-* API only accepts strings, but this is the idea

```jsx
const onFailed = e => e.target.style.display = 'none'

{/* when failed on full */}
<a href='full.jpg' data-failed={onFailed}>
  {/* when failed on tiny */}
  <img src='tiny.jpg' onerror={onFailed} />
</a>
```

I can also give a pr for this if you like.

**Comment by craigbuckler** [comment]
Thanks @cheuksing - that's an interesting idea. Do you have experience of situations where images fail to load? How did you handle it?

The preview images should be tiny and are less likely to timeout (they could be base64 inline images, too).  

The large images are more likely to fail since connection could occur much later and involve larger files. We could detect the connection, add timeouts, and retry at another time. That could be quite efficient, but I'd probably do it within the library. Would you need a callback?

Would many people find it useful given the increase in file size?

**Comment by cheuksing** [comment]
@craigbuckler 
I have a grid list of images. One / two of those images sometimes fail when users using a large screen.
Also, sometimes one of the CDNs need longer time to sync, it may lead to 404 after users updated images in some rare cases.
If callbacks are not allowed, I think we can have these 2 options. I think this 2 will handle 99% of cases.
data-retry: will retry X times if failed to load
data-hide: if all X retries are failed, it optionally set the image to display none. So there is no ugly 'browser failed image logo', and devs can show any placeholders or descriptions they want.
===================
Sorry for the late reply, but I was rebuilding my desktop this weekend and have no access to pc.

**Comment by craigbuckler** [comment]
Do you have an example URL?

My first thought: if you're showing lots of images, are they quite small and download quickly? Check your image dimensions and sizes.

I presume the onload event never fires so the primary image never appears?

I'll have a think about detecting load errors and attempting again. It's a bit of an edge case - especially since a user is unlikely to wait around - but it should be possible within a few lines of code.

**Comment by cheuksing** [comment]
@craigbuckler 
The tiny images almost never fail. But after multiple tiny images are loaded, the browser starts downloading the full images. This is usually when it fails. In my case, images are 512*512, and there are 20 of them per page.

Btw, I don't think it is necessary to handle 1st image failed in this library.
It almost never happens and devs already have direct control of it, unlike the 2nd, 3rd ... images with higher resolution.

**Comment by craigbuckler** [comment]
I'm looking at some options.

However, 512x512 does seem quite large. I presume they're not shown that size so you might be able to shrink them down and improve download reliability.

**Comment by cheuksing** [comment]
@craigbuckler Thanks. I will try to reduce the image sizes, such as 256 * 256. Please let me know if there are any updates. It would still very nice to have some error handle options, since not every user can have a very stable network, it depends on the user's country and location.

**Comment by craigbuckler** [comment]
I'm trying some options now.

Remember that halving the image dimensions reduces the area (and possibly the file size) by 75%. You may be able to use the `srcset` to serve smaller images according to screen size too.

**Comment by cheuksing** [comment]
Thanks a lot. This is very useful. I will try `srcset`. It seems very handy. :D

**Comment by craigbuckler** [comment]
Just pushed another release: v1.4.0.

This detects download errors and retries after 3s then 6s. The preview image is not replaced if the large image fails to load.

Thanks for the suggestion - I've credited you in the README.
