### ISSUE TITLE
Bootstrap carousel images are not loaded.

### ISSUE THREAD

**Issue by navanshu** [craigbuckler/progressive-image.js#31]
It is able to load only the first image on the rest of images it waits for ever.

**Comment by craigbuckler** [comment]
It loads images as their containers are scrolled into view. Any that are in view are immediately loaded.

If that's not your experience, please can you provide some demonstration code and let me know what browser you're using.

**Comment by craigbuckler** [comment]
Thinking about this some more, carousel images *may* be at the same vertical position on the page. If that's the case, the images would load immediately even when they're off-screen.

However, if the carousel dynamically changes the CSS to make images appear (`display` none => block), the full image would not load unless you scrolled the page.

But I can't really tell without an example.

That said, `progressive-image.js` is not really suitable for a carousel. You want images to be ready *before* they slide into view - otherwise, the loading could occur more slowly than the next slide/image appearing.

My advice: don't do this. You could lazy-load images, but need to trigger that within the carousel system *before* they're required.
