### ISSUE TITLE
Background-image not loading smoothly

### ISSUE THREAD

**Issue by lovecoding-git** [craigbuckler/progressive-image.js#39]
Hi

Thanks for such great package.
Background image lazy loading didn't work smoothly.

When I load page first, lower pixel background image is loading first.
And when it is replaced with higher quality of background image, it didn't work smoothly.  (first image  disappears and there is white background for a quite while and then second image appears)

When I reload page, it works well. (I think when i reload, it works because browser has it in cache. But when I reload page with CTRL+F5,  there is same issue.)

Could you please solve this issue? Thanks

**Comment by lovecoding-git** [comment]
I just captured moment. Here is screenshots.

![Screenshot_1](https://user-images.githubusercontent.com/61916777/88188218-1b9b8c80-cc6a-11ea-91a7-8953f02a7d67.png)
![Screenshot_2](https://user-images.githubusercontent.com/61916777/88188221-1c342300-cc6a-11ea-9f98-d7fdde7abc00.png)
![Screenshot_3](https://user-images.githubusercontent.com/61916777/88188231-1e967d00-cc6a-11ea-95b5-2a6fdffe7fcd.png)


My code is here.

```
<style>
        .bgimg {
            background-image: url('/assets/img/front/slider/page.jpg');
        }
        .bgimg.replace {
            background-image: url('/assets/img/front/slider/page-sm.jpg');
        }
    </style>
```
```
<div class="page-top-info bgimg progressive replace">
    <div class="container text-center">
        <h1 class="text-white">Blog</h1>
    </div>
</div>
```

**Comment by craigbuckler** [comment]
Thanks @lovecoding-git 

It'd be good to see an example URL, but that could happen if your images are quite large (in filesize KBs).

You're using this code to apply a different background image. While it supports that, the browser controls how it gets loaded. I suspect it loads `page-sm.jpg` only, then removes that image while `page.jpg` is loading. If that takes a second or two, you'd see a white background.

Options:

1. Optimize your image. It shouldn't be more than a couple of hundred Kb.
1. Make the background green so the change is less obvious.
1. Preload the large image in your HTML `<head>`:

```html
<link rel="preload" href="/assets/img/front/slider/page.jpg" as="image">
```

You can do all three, but it'd be preferable to use an actual `<img>` rather than a CSS background and overlay text on the top of it. You'd get the loading animation and there'd be no flash of color.

I hope that helps.

**Comment by lovecoding-git** [comment]
Background Image size is 2.33 MB. :)
It worked well in <img> tag even though image size is 10 MB.
Thank you!
