### ISSUE TITLE
Retaining the img class

### ISSUE THREAD

**Issue by Alntjan** [craigbuckler/progressive-image.js#4]
Hi!
Is it possible to retain the <img> class of the tiny picture? When it gets replaced all classes are removed.
Cheers,

**Comment by craigbuckler** [comment]
Hi,

Actually, that whole image is removed from the DOM - not just the class. That has to be done otherwise it causes rendering issues in some browsers.

While it would be possible to copy classes across, could you apply the class to the container instead? It could then apply to every image within it.

Hope that helps.

**Comment by Alntjan** [comment]
Wow ok no problem, i was just wondering ^_^
